from textual import work
from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import Header, Footer, Select, Button, RichLog, TextArea, Label

from model_manager import AVAILABLE_MODELS, is_model_downloaded, download_model_weights
from model_inference import InferenceEngine

class LocalLLMApp(App):
    CSS = """
    Screen {
        align: center top;
    }
    #sidebar {
        width: 30%;
        border-right: solid $accent;
        padding: 1;
    }
    #main-chat {
        width: 70%;
        padding: 1;
    }
    RichLog {
        background: $boost;
        border: tall $background;
        height: 75%;
    }
    TextArea {
        height: 20%;
    }
    .margin-top {
        margin-top: 1;
    }
    """

    def __init__(self):
        super().__init__()
        self.engine = None

    def compose(self) -> ComposeResult:
        yield Header()
        with Horizontal():
            # Left Sidebar: Model Management
            with Vertical(id="sidebar"):
                yield Label("1. Select Model:")
                yield Select(
                    options=[(name, name) for name in AVAILABLE_MODELS.keys()],
                    id="model-selector"
                )
                yield Button("Download Model", id="download-btn", variant="primary", classes="margin-top")
                yield Label(id="status-text", classes="margin-top")
            
            # Right Panel: Chat Interface
            with Vertical(id="main-chat"):
                yield RichLog(id="chat-log", highlight=True, markup=True)
                yield TextArea(placeholder="Type your prompt here... (Ctrl+S to submit)", id="prompt-input")
                yield Button("Send Prompt", id="send-btn", variant="success")
        yield Footer()

    def on_mount(self) -> None:
        self.query_one("#download-btn").disabled = True
        self.query_one("#prompt-input").disabled = True
        self.query_one("#send-btn").disabled = True

    def on_select_changed(self, event: Select.Changed) -> None:
        """Fires when a user selects a model from the dropdown."""
        if event.value:
            model_name = str(event.value)
            if is_model_downloaded(model_name):
                self.query_one("#download-btn").label = "Load Model"
                self.query_one("#status-text").update("[green]Downloaded locally.[/green]")
            else:
                self.query_one("#download-btn").label = "Download from HF"
                self.query_one("#status-text").update("[yellow]Requires download.[/yellow]")
            self.query_one("#download-btn").disabled = False

    @work(exclusive=True, thread=True)
    def action_manage_model(self, model_name: str) -> None:
        """Worker thread to handle downloading or loading weights without locking the UI."""
        status_label = self.query_one("#status-text")
        btn = self.query_one("#download-btn")
        
        if not is_model_downloaded(model_name):
            status_label.update("[yellow]Downloading... please wait...[/yellow]")
            btn.disabled = True
            # Downloads directly to local user directory path
            weights_path = download_model_weights(model_name)
        else:
            from model_manager import get_local_model_path
            weights_path = get_local_model_path(model_name)
            
        status_label.update("[yellow]Loading weights into PyTorch...[/yellow]")
        
        # Instantiate your custom inference pipeline
        self.engine = InferenceEngine(weights_path)
        
        status_label.update("[green]Model Active & Ready![/green]")
        self.query_one("#prompt-input").disabled = False
        self.query_one("#send-btn").disabled = False

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "download-btn":
            selected_model = self.query_one("#model-selector").value
            if selected_model:
                self.action_manage_model(str(selected_model))
                
        elif event.button.id == "send-btn":
            self.process_prompt()

    @work(exclusive=True, thread=True)
    def process_prompt(self) -> None:
        """Worker thread that streams tokens generated by PyTorch."""
        input_widget = self.query_one("#prompt-input", TextArea)
        chat_log = self.query_one("#chat-log", RichLog)
        
        prompt = input_widget.text.strip()
        if not prompt or not self.engine:
            return

        chat_log.write(f"\n[bold cyan]User:[/bold cyan] {prompt}\n")
        chat_log.write("[bold green]LLM: [/bold green]")
        
        input_widget.text = "" # Clear input
        
        # Stream the tokens seamlessly into the Textual RichLog widget
        for token in self.engine.generate_stream(prompt):
            chat_log.write(token, scroll_end=True)

if __name__ == "__main__":
    app = LocalLLMApp()
    app.run()